### ISSUE TITLE
UCA - IllegalStateException - Already building

### ISSUE THREAD

**Issue by rettichlp** [UnicacityAddon/unicacityaddon-addon#711]
### Description

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-07-05 22:03
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at buk.a(BufferBuilder.java:309)
	at bvd.a(SourceFile:236)
	at bvd.c(SourceFile:197)
	at bib.redirect$zej000$labyMod$renderFramebuffer(SourceFile:7399)
	at bib.az(SourceFile:1045)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:214)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:67)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at buk.a(BufferBuilder.java:309)
	at bvd.a(SourceFile:236)
	at bvd.c(SourceFile:197)

-- Affected level --
Details:
	Level name: MpServer
	All players: 4 total; [bud['RettichLP'/108270, l='MpServer', x=35.45, y=101.00, z=252.11], bue['shynox78'/84699, l='MpServer', x=42.70, y=70.00, z=239.70], bue['KVeTZaWHgPAlZBe'/73290, l='MpServer', x=37.51, y=104.00, z=252.48], bue['Gelegenheitsdieb'/107582, l='MpServer', x=14.33, y=75.00, z=252.10]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (100,69,156), Chunk: (at 4,4,12 in 6,9; contains blocks 96,0,144 to 111,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2296 game time, 41724851 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 60 total; [bud['RettichLP'/108270, l='MpServer', x=35.45, y=101.00, z=252.11], bue['shynox78'/84699, l='MpServer', x=42.70, y=70.00, z=239.70], acd['Painting'/66, l='MpServer', x=56.97, y=106.00, z=251.50], bue['KVeTZaWHgPAlZBe'/73290, l='MpServer', x=37.51, y=104.00, z=252.48], acd['Painting'/67, l='MpServer', x=53.50, y=107.00, z=261.97], acd['Painting'/25, l='MpServer', x=9.03, y=30.00, z=253.00], acd['Painting'/26, l='MpServer', x=6.03, y=63.50, z=249.00], afk['entity.MinecartRideable.name'/95119, l='MpServer', x=50.52, y=68.50, z=235.99], acd['Painting'/27, l='MpServer', x=6.03, y=63.50, z=247.50], acd['Painting'/28, l='MpServer', x=13.00, y=76.50, z=246.97], acd['Painting'/29, l='MpServer', x=13.00, y=77.00, z=248.03], acd['Painting'/30, l='MpServer', x=11.00, y=65.00, z=254.97], acd['Painting'/31, l='MpServer', x=6.03, y=65.50, z=249.00], acd['Painting'/32, l='MpServer', x=6.03, y=64.50, z=248.00], acd['Painting'/33, l='MpServer', x=6.03, y=65.50, z=247.50], acd['Painting'/34, l='MpServer', x=6.03, y=64.50, z=249.50], bue['Gelegenheitsdieb'/107582, l='MpServer', x=14.33, y=75.00, z=252.10], acd['Painting'/38, l='MpServer', x=10.50, y=18.50, z=266.97], acd['Painting'/24, l='MpServer', x=5.00, y=77.00, z=233.97], acd['Painting'/25, l='MpServer', x=9.03, y=30.00, z=253.00], acd['Painting'/26, l='MpServer', x=6.03, y=63.50, z=249.00], acd['Painting'/27, l='MpServer', x=6.03, y=63.50, z=247.50], acd['Painting'/28, l='MpServer', x=13.00, y=76.50, z=246.97], acd['Painting'/29, l='MpServer', x=13.00, y=77.00, z=248.03], afk['entity.MinecartRideable.name'/92447, l='MpServer', x=41.03, y=68.50, z=235.83], acd['Painting'/30, l='MpServer', x=11.00, y=65.00, z=254.97], afk['entity.MinecartRideable.name'/99231, l='MpServer', x=-10.06, y=68.50, z=235.83], acd['Painting'/31, l='MpServer', x=6.03, y=65.50, z=249.00], acd['Painting'/32, l='MpServer', x=6.03, y=64.50, z=248.00], acd['Painting'/33, l='MpServer', x=6.03, y=65.50, z=247.50], afk['entity.MinecartRideable.name'/82336, l='MpServer', x=28.41, y=68.50, z=289.52], acd['Painting'/34, l='MpServer', x=6.03, y=64.50, z=249.50], acd['Painting'/24, l='MpServer', x=5.00, y=77.00, z=233.97], abz['§8/§3buy'/421, l='MpServer', x=47.00, y=67.80, z=203.00], acd['Painting'/38, l='MpServer', x=10.50, y=18.50, z=266.97], acd['Painting'/39, l='MpServer', x=12.50, y=18.50, z=266.97], acd['Painting'/40, l='MpServer', x=11.50, y=18.50, z=266.97], acd['Painting'/41, l='MpServer', x=10.00, y=30.00, z=262.03], acd['Painting'/42, l='MpServer', x=11.50, y=30.00, z=259.97], acd['Painting'/43, l='MpServer', x=9.03, y=30.00, z=257.50], acd['Painting'/44, l='MpServer', x=8.50, y=60.00, z=268.97], acd['Painting'/45, l='MpServer', x=11.00, y=65.00, z=256.03], acd['Painting'/46, l='MpServer', x=11.97, y=65.00, z=257.50], acd['Painting'/47, l='MpServer', x=5.00, y=71.00, z=261.03], acd['Painting'/48, l='MpServer', x=5.00, y=71.00, z=259.97], aab['OGTEA'/101304, l='MpServer', x=-0.16, y=88.00, z=245.28], bue['Gelegenheitsdieb'/107582, l='MpServer', x=14.33, y=75.00, z=252.10], aab['Vladimir'/107966, l='MpServer', x=10.72, y=75.56, z=245.55], afk['entity.MinecartRideable.name'/107584, l='MpServer', x=13.27, y=68.50, z=267.05], acd['Painting'/66, l='MpServer', x=56.97, y=106.00, z=251.50], acd['Painting'/67, l='MpServer', x=53.50, y=107.00, z=261.97], afk['entity.MinecartRideable.name'/98245, l='MpServer', x=-10.09, y=68.50, z=209.72], afk['entity.MinecartRideable.name'/73291, l='MpServer', x=38.29, y=68.50, z=268.57], bue['KVeTZaWHgPAlZBe'/73290, l='MpServer', x=37.51, y=104.00, z=252.48], bue['shynox78'/84699, l='MpServer', x=42.70, y=70.00, z=239.70], aam['Maxim'/100320, l='MpServer', x=56.09, y=105.06, z=251.63], aam['Emi'/108271, l='MpServer', x=38.00, y=105.00, z=254.00], afk['entity.MinecartRideable.name'/101875, l='MpServer', x=40.89, y=68.50, z=234.51], afk['entity.MinecartRideable.name'/82425, l='MpServer', x=-11.09, y=68.50, z=232.62], afk['entity.MinecartRideable.name'/91774, l='MpServer', x=39.55, y=68.50, z=236.01]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bsb.a(WorldClient.java:532)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:433)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:214)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:67)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 386670680 bytes (368 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	LWJGL: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	OpenGL: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	GL Caps: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	Using VBOs: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	Is Modded: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	Type: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	Resource Packs: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	Current Language: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	Profiler Position: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	CPU: AMD Radeon RX 6600 XT GL version 4.6.0 Compatibility Profile Context 23.5.2.230523, ATI Technologies Inc.
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 23.5.2.230523
	OpenGlRenderer: AMD Radeon RX 6600 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

-- LabyMod Details --
	Version: 4.0.0+824 snapshot/7ae34c6e
	Commit Reference: 7ae34c6e
	Theme: Fancy
	Loaded Addons: voicechat(0.2.18), unicacityaddon(2.1.0-dev), optifine(1.0.24), spotify(1.0.11), flux(1.2.4), teamspeak(1.0.4), chattime(1.0.6)

-- OpenGL Details --
	Available versions: OpenGL11, OpenGL12, OpenGL13, OpenGL14, OpenGL15, OpenGL20, OpenGL21, OpenGL30, OpenGL31, OpenGL32, OpenGL33, OpenGL40, OpenGL41, OpenGL42, OpenGL43, OpenGL44, OpenGL45, OpenGL46
Framebuffer:
	Max. Color Attachments: 0
	Max. Renderbuffer Size: 0
	Max. Samples: 0
Shader:
	Max. Vertex Uniform Components: 0
	Max. Fragment Uniform Components: 0
	Max. Varying Floats: 0
	Max. Vertex Attributes: 0
	Max. Texture Image Units: 0
	Max. Vertex Texture Image Units: 0
	Max. Combined Texture Image Units: 0
	Max. Texture Coords: 0
	Max. Uniform Buffer Bindings: 0
	Max. Uniform Block Size: 0
	Max. Vertex Output Components: 0
```

LabyMod version: `4`

Minecraft version: `1.12.2`

Addon version: `2.1.0-dev`

<hr>

#### Reporter (You)

- [x] Issue name according to naming conventions added (`UCA - <short description>`)
- [x] Bug description added and information provided

#### Refinement (We)

- [ ] #717
- [ ] Milestone linked
- [ ] Contributor assigned

#### Start issue (We)

- [ ] Branch according to naming convention created (`bug/UCA-<issue-number>-<short-description>`)
- [ ] Pull request according to naming convention created (`bug/UCA-<issue-number>-<short-description>`)
- [ ] Reviewer assigned to pull request

**Comment by rettichlp** [comment]
No further occurrences, probably fixed by LabyMod
